### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by spyhunter99** [foospidy/payloads#2]
cool repo, but i'm not sure how to go about using any of this data. Do you have any pointers or tips on usage?

**Comment by n00py** [comment]
Most people probably use them with Burp Suite, you could use them with any fuzzing tool.

**Comment by spyhunter99** [comment]
gotcha, thanks

**Comment by foospidy** [comment]
I've also used bash scripts to read files and loop through the payloads (sending each payload with the curl command).

**Comment by spyhunter99** [comment]
thanks @foospidy
